// generated by vite-plugin-components
// read more https://github.com/vuejs/vue-next/pull/3399

declare module 'vue' {
  export interface GlobalComponents {
    Email: typeof import('./src/components/fields/Email.vue')['default']
    Explorer: typeof import('./src/components/Explorer.vue')['default']
    Fields: typeof import('./src/components/shape/Fields.vue')['default']
    IonBackButton: typeof import('@ionic/vue')['IonBackButton']
    IonButton: typeof import('@ionic/vue')['IonButton']
    IonButtons: typeof import('@ionic/vue')['IonButtons']
    IonChip: typeof import('@ionic/vue')['IonChip']
    IonContent: typeof import('@ionic/vue')['IonContent']
    IonHeader: typeof import('@ionic/vue')['IonHeader']
    IonIcon: typeof import('@ionic/vue')['IonIcon']
    IonImg: typeof import('@ionic/vue')['IonImg']
    IonInput: typeof import('@ionic/vue')['IonInput']
    IonItem: typeof import('@ionic/vue')['IonItem']
    IonItemOption: typeof import('@ionic/vue')['IonItemOption']
    IonItemOptions: typeof import('@ionic/vue')['IonItemOptions']
    IonItemSliding: typeof import('@ionic/vue')['IonItemSliding']
    IonLabel: typeof import('@ionic/vue')['IonLabel']
    IonList: typeof import('@ionic/vue')['IonList']
    IonListHeader: typeof import('@ionic/vue')['IonListHeader']
    IonPage: typeof import('@ionic/vue')['IonPage']
    IonRouterOutlet: typeof import('@ionic/vue')['IonRouterOutlet']
    IonSearchbar: typeof import('@ionic/vue')['IonSearchbar']
    IonSlide: typeof import('@ionic/vue')['IonSlide']
    IonSlides: typeof import('@ionic/vue')['IonSlides']
    IonTabBar: typeof import('@ionic/vue')['IonTabBar']
    IonTabButton: typeof import('@ionic/vue')['IonTabButton']
    IonTabs: typeof import('@ionic/vue')['IonTabs']
    IonText: typeof import('@ionic/vue')['IonText']
    IonTextarea: typeof import('@ionic/vue')['IonTextarea']
    IonThumbnail: typeof import('@ionic/vue')['IonThumbnail']
    IonTitle: typeof import('@ionic/vue')['IonTitle']
    IonToggle: typeof import('@ionic/vue')['IonToggle']
    IonToolbar: typeof import('@ionic/vue')['IonToolbar']
    ItemMini: typeof import('./src/components/ItemMini.vue')['default']
    Number: typeof import('./src/components/fields/Number.vue')['default']
    PickFieldModal: typeof import('./src/components/modals/PickFieldModal.vue')['default']
    SubmitGroup: typeof import('./src/components/auth/SubmitGroup.vue')['default']
    Text: typeof import('./src/components/fields/Text.vue')['default']
    Toggle: typeof import('./src/components/fields/Toggle.vue')['default']
  }
}

export { }
